### ISSUE TITLE
What happened to class mil.nga.geopackage.tiles.TileDraw

### ISSUE THREAD

**Issue by spyhunter99** [ngageoint/geopackage-java#28]
Sorry to bug you all a work. I'm trying to upgrade from 1.1.0 to 1.2.0

Looks like it was deleted or renamed with commit 3d253c4db1702e0e427be628206f6a121b45d392 in may of 2016. What's the replacement?

**Comment by bosborn** [comment]
In the same spirit as ngageoint/geopackage-android#18, it was replaced by [TileRetriever](https://github.com/ngageoint/geopackage-java/blob/b6310ba8862fe968f2c579916fde2a69375f3af4/src/main/java/mil/nga/geopackage/tiles/TileRetriever.java) and [TileCreator](https://github.com/ngageoint/geopackage-java/blob/b6310ba8862fe968f2c579916fde2a69375f3af4/src/main/java/mil/nga/geopackage/tiles/TileCreator.java) to separate tile creation logic from XYZ tiles.  [GeoPackageTileRetriever](https://github.com/ngageoint/geopackage-java/blob/b6310ba8862fe968f2c579916fde2a69375f3af4/src/main/java/mil/nga/geopackage/tiles/GeoPackageTileRetriever.java) is the retriever implementation you'd use and currently the only one.

TileWriter in commit 3d253c4 is an example of changing from TileDraw to GeoPackageTileRetriever.  Key parts include...

```
TileDao tileDao = geoPackage.getTileDao(tileTable);

...

GeoPackageTileRetriever retriever = null;

if (rawImage) {
    retriever = new GeoPackageTileRetriever(tileDao);
} else {
    retriever = new GeoPackageTileRetriever(tileDao, width, height, imageFormat);
}

...

GeoPackageTile geoPackageTile = retriever.getTile(x, y, zoomLevel);
if (geoPackageTile != null) {

    ...

    if (geoPackageTile.getImage() != null) {
        // geoPackageTile.getImage() is the tile as a BufferedImage
        // ImageUtils.writeImageToBytes if you need bytes
    } else {
        // geoPackageTile.getData() is the raw image bytes
        // ImageUtils.getImage if you need a BufferedImage
    }
}

```

**Comment by spyhunter99** [comment]
thanks
