### ISSUE TITLE
NSG Profile Support

### ISSUE THREAD

**Issue by geospatialmapmashup** [ngageoint/geopackage-java#36]
Has the GeoPackage JAVA library been updated to support the NGA's NSG GeoPackage Tiling Profile Specification?  (NSG) GeoPackage Encoding Standard 2.0
Interoperability Standard
(2016-09-14)

Version 2.0
(NSG) GeoPackage Encoding Standard 2.0
Interoperability Standard
(2016-09-14)

**Comment by bosborn** [comment]
Please see ngageoint/GeoPackage#4

**Comment by bosborn** [comment]
NSG is fully supported except for NGA CRS authored WKT coordinate system values.  This can be supported currently by providing those values in advance.  Will be handled automatically as part of: ngageoint/simple-features-proj-java#1
