### ISSUE TITLE
Example on how to add features to a gpkg missing

### ISSUE THREAD

**Issue by ISchwarz23** [ngageoint/geopackage-java#38]
I am currently failing to use the library to create a GeoPackage file and write my feature data to it. I was not able to find an example in the readme file. 

Would it be possible to add an example on how to add a simple Geometry like a Point to a newly created GeoPackage? This would include the creation of a "feature table" and the adding to the "geometry columns table".

As alternative I would be happy to get a simple answer to this question, but I guess there are other developers who would find this pretty helpful.

**Comment by bosborn** [comment]
This is still only on the develop branch, but take a look at [GeoPackageExample](https://github.com/ngageoint/geopackage-java/blob/develop/src/test/java/mil/nga/geopackage/test/GeoPackageExample.java).  The purpose is to generate a test GeoPackage that passes all of the [OGC GeoPackage test cases](https://github.com/opengeospatial/ets-gpkg12).

The [createFeatures](https://github.com/ngageoint/geopackage-java/blob/1a477e53562b89cb483b7162ce54f85eb641aad5/src/test/java/mil/nga/geopackage/test/GeoPackageExample.java#L225) method should provide the examples to get you going.

There are also some examples[ in the tests](https://github.com/ngageoint/geopackage-java/blob/93497593c439305c22ddd604a6dd73abc513cb79/src/test/java/mil/nga/geopackage/test/TestSetupTeardown.java#L371).

**Comment by ISchwarz23** [comment]
Thank you very much :+1:
