### ISSUE TITLE
Consider supporting the OGC GeoPackage Extension for Tiled Gridded Coverage Data (17-066r1) 

### ISSUE THREAD

**Issue by ghobona** [ngageoint/geopackage-java#44]
Consider supporting the OGC GeoPackage Extension for Tiled Gridded Coverage Data (17-066r1) http://docs.opengeospatial.org/is/17-066r1/17-066r1.html

The document can be found on the main geopackage standard page https://www.opengeospatial.org/standards/geopackage

The extension provides the means of storing raster data such as GeoTIFF-encoded imagery in a GeoPackage.

**Comment by bosborn** [comment]
Support was added a year ago, starting in version [2.0.1](https://github.com/ngageoint/geopackage-java/releases/tag/2.0.1).  

See:
* in [geopackage-java](https://github.com/ngageoint/geopackage-java/tree/master/src/main/java/mil/nga/geopackage/extension/coverage)
* in [geopackage-core-java](https://github.com/ngageoint/geopackage-core-java/tree/master/src/main/java/mil/nga/geopackage/extension/coverage)
* [tests](https://github.com/ngageoint/geopackage-java/tree/master/src/test/java/mil/nga/geopackage/test/extension/coverage)
* [creation example](https://github.com/ngageoint/geopackage-java/blob/bf915ccedd9fddd12a164b8f57406620df0f8c57/src/test/java/mil/nga/geopackage/test/GeoPackageExample.java#L1103)

**Comment by ghobona** [comment]
That's excellent! Great job.
Thanks.
