### ISSUE TITLE
Efficient way to get unique values from a column

### ISSUE THREAD

**Issue by thorsten-reitz** [ngageoint/geopackage-java#47]
**State your question**
I am looking for an efficient way to get something like a DISTINCT query to get unique values from a non-geometry column from a Geopackage table with many millions of objects. Iterating through all features takes several hours.

**Additional context**
The data in question is the transport network graph for all of Austria, which is available from here: https://www.data.gv.at/katalog/dataset/intermodales-verkehrsreferenzsystem-osterreich-gip-at-beta/resource/0434feec-210f-4a95-b60c-a948a0b291e9

**Comment by bosborn** [comment]
The distinct keyword isn't in any of the feature / user dao query shortcut methods.  I might be able to add that later.  For now you can just run a raw query.

```
FeatureDao dao = geoPackage.getFeatureDao("table_name");
String column = "column_name";
FeatureResultSet results = dao.getUserDb().rawQuery(
	"SELECT DISTINCT " + column + " FROM " + dao.getTableName(), null);
while(results.moveToNext()) {
	Object value = results.getValue(0);
	//results.getString(0);
	//results.getInt(0);
	//results.getBlob(0);
	//results.getLong(0);
	//results.getShort(0);
	//results.getDouble(0);
	//results.getFloat(0);
	System.out.println(value);
}
results.close();
```

**Comment by thorsten-reitz** [comment]
Thanks a lot! In case you're wondering, we're adding Geopackage reader/writer support to hale studio: https://github.com/halestudio/hale/

**Comment by bosborn** [comment]
@thorsten-reitz 
Ability added in version [4.0.0](https://github.com/ngageoint/geopackage-java/releases/tag/4.0.0).  Upon upgrading, the above example can be changed to:

```
FeatureDao dao = geoPackage.getFeatureDao("table_name");
String column = "column_name";
FeatureResultSet results = dao.query(true, new String[] { column });
while (results.moveToNext()) {
	Object value = results.getValue(column);
	System.out.println(value);
}
results.close();
```

**Comment by thorsten-reitz** [comment]
@bosborn Great! And thanks for letting us know - @florianesser @stempler something to take into account for the next hale studio milestone.
