### ISSUE TITLE
FeatureResultSet.moveToFirst() does nothing.

### ISSUE THREAD

**Issue by AKShaw** [ngageoint/geopackage-java#50]
Please fill out as much known and relevant information as possible.

#### Version Information:

  * GeoPackage Java Version: 3.4.0
  * GeoPackage Java Source: Maven repo
  * IDE Name & Version: IntelliJ march 2020 version
  * Java Version: JDK 1.8
  * Platform & OS: Windows

#### Expected Results:

  * What did you expect to happen?

Expected cursor to move to the first row of the table

#### Observed Results:

  * What happened instead?
Cursor didnt move at all
  * How often does this occur?
100%

#### Output:

  * Any logs, errors, or output messages?
0
1
2
2

#### Steps to Reproduce:

  1. Create a non empty FeatureResultSet by querying a DAO
  2. Print resultSet.getPosition()
  3. Call resultSet.moveToNext()
  4. Repeat 2, 3 as many times as you want
  5. Call resultSet.moveToFirst()
  6.  Print resultSet.getPosition()
#### Relevant Code:

```java
FeatureResultSet frs = dao.queryForAll();
System.out.println("Current pos: " + frs.getPostition());
frs.moveToNext();
System.out.println("Current pos: " + frs.getPostition());
frs.moveToNext();
System.out.println("Current pos: " + frs.getPostition());
frs.moveToFirst();
System.out.println("Current pos: " + frs.getPostition());
```

#### Test Files:

  * Links to any files needed for testing?

#### Additional Information:

  * Any additional configuration, data, or information that might help with the issue?

**Comment by bosborn** [comment]
The utilized SQLite JDBC library is TYPE_FORWARD_ONLY (statements can not be created with scroll types).  For your example, close the result set and perform the query again.  Made [a few changes](https://github.com/ngageoint/geopackage-java/commit/fb3da6cd2aabba2ca2cdbabce748728411d4a223) for the next version that will throw an exception in that case.

**Comment by bosborn** [comment]
The [geopackage-core-java](https://github.com/ngageoint/geopackage-core-java) interface is shared by both this and the [geopackage-android](https://github.com/ngageoint/geopackage-android) library, which is why some of the implementations differ.
