### ISSUE TITLE
Feature comparison between geopackage-java and geotools implementation?

### ISSUE THREAD

**Issue by smsiebe** [ngageoint/geopackage-java#51]
Has anyone done or seen a feature comparison between the geopackage-java project and the geotools geopackage implementations?  It would be useful in determining the value of using this project.

Thanks!

**Comment by bosborn** [comment]
You probably won't receive unbiased opinions from authors of a project.  You could perform your own comparison or ask somewhere like [GIS Stack Exchange](https://gis.stackexchange.com/).

This project is

- Openly licensed as [MIT](https://choosealicense.com/licenses/mit/) (less restrictive than [LGPL](https://choosealicense.com/licenses/lgpl-3.0/))
- Actively used and maintained by the U.S. National Geospatial-Intelligence Agency (NGA)
- [OGC certified](https://www.ogc.org/resource/products?display_opt=1&specid=872&org_match=US%20National%20Geospatial-Intelligence%20Agency%20(NGA))
- Shares core source with [GeoPackage Android](https://github.com/ngageoint/geopackage-android), an [Official OGC GeoPackage Reference Implementation](https://www.ogc.org/resource/products/details/?pid=1626)
